# Jekyll configuration

name: Kotiya Sanae
description: A blog to write things.

# Url is currently only used only for the RSS feed in feed.xml
url: https://github.com/Trytwice/Trytwice.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: 

author: Kotiya Sanae
copyright: 2017-2018. Powered by Vim, Git, Jekyll and jekyll-clean-dark theme.

share:
  facebook: false
  twitter: true
  gplus: false
  linkedin: false
  pinterest: false
  email: true

social:
  github: Trytwice
  twitter: WuTianhong
  #stackoverflow: ''
  #linkedin:
  #instagram: ''
  #lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-120211088-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: kotiyasanae
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#gems: [jekyll-paginate-v2]
#paginate: 2

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false

#exclude: ['README.md', 'LICENSE']
